name: Visit Tracker
description: A full-stack application for tracking representative visits with PostgreSQL and Google Maps integration
icon: 📍
services:
  - name: web
    type: web
    env:
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET:
        generate: true
      DATABASE_URL:
        serviceRef: postgres
      POSTGRES_PASSWORD:
        serviceRef:
          service: postgres
          property: PGPASSWORD
      CLIENT_URL: https://${{RAILWAY_PUBLIC_DOMAIN}}
      REACT_APP_API_URL: https://${{RAILWAY_PUBLIC_DOMAIN}}/api
      GOOGLE_MAPS_API_KEY:
        prompt: Enter your Google Maps API Key (optional)
    build:
      buildCommand: npm install && cd client && npm install && REACT_APP_API_URL=https://${{RAILWAY_PUBLIC_DOMAIN}}/api npm run build && cd ..
    deploy:
      startCommand: npm start
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 10
    healthcheck:
      path: /api/health
      interval: 30
      timeout: 10
  - name: postgres
    type: postgresql
    plan: starter
